### ISSUE TITLE
State not updated when window is popped out

### ISSUE THREAD

**Issue by jbeard4** [andrewcapodieci/golden-layout-react-redux#12]
When you pop out the TestComponentContainer, clicking increment/decrement buttons fail to update the state of the popped out window. Maybe the example needs to be updated to use `glEventHub` to receive events from the parent window and map them to component props.

**Comment by andrewcapodieci** [comment]
That's correct I definitely did not add support for window popping. The showPopoutIcon in the config should be disabled. If you'd like to add this functionality to the example I'd love to support your PR.
