### ISSUE TITLE
resize the layout

### ISSUE THREAD

**Issue by jerronl** [andrewcapodieci/golden-layout-react-redux#8]
how can we change the layout size when the window resizes? I tried something like following:

```
    render() {
        return (
            <div id="goldenLayout" style={{height:this.state.ht+"px"}}/>
        );
    }

```
But only the outer container changed. The layout did not changed accordingly. seems I need to call `layout.updateSize();`
But when to call it?

**Comment by andrewcapodieci** [comment]
@jerronl  you need to do this:
```
        $(window).on('resize', () => {
            layout.updateSize();
        });
```
and whatever css that goes along with it...if you add it to this repo feel free to make a PR :smile:

**Comment by jerronl** [comment]
OK, just created a PR. However I still didn't get the size updated always in time. Now the layout.updateSize() was called **before** the outer container's size change instead of after.

**Comment by andrewcapodieci** [comment]
should be fixed by latest merge; you will have to play with the css to get it exactly right, as currently there is a scrollbar with a very small range despite resizes occuring.
